name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Set the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        

    - name: Run tests
      run: |
        python -m unittest discover -p 'test_*.py'
